services:
  _defaults:
    autowire: true
    public: false

  oxid.ccevent.git:
    class: Sioweb\CCEvent\Git\Command\AddGitCommand
    tags:
      - { name: 'console.command', command: 'ccevent:add:git', description: 'Add git directory to configured composer packages' }
    bind:
      $projectDir: '%kernel.project_dir%'
    public: true
